server:
  port: 8082

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:h2:mem:accountdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console


  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: docker  # ← CORRECTED SYNTAX
  kafka:
    bootstrap-servers: kafka:29092

vbank:
  kafka:
    topic: logging-topic
  scheduling:
    account-cleanup:
      enabled: true
      fixed-rate: 3600000  # 1 hour in milliseconds
